services: docker
language: python

jobs:
  include:
  - stage: build
    env: CustomProperties
    install:
      - docker run -v $(pwd)/demos/projects:/io/data -v $(pwd)/plugins:/io/plugins -d -p 8015:80 openquake/qgis-server:stable
    script:
      - sleep 10 && curl http://localhost:8015/ogc/nepal_hazard?service=WMS&request=GetCapabilities
      - curl http://localhost:8015/ogc/nepal_hazard?service=EWMS&request=GetLayerCustomProperties

  - stage: build
    env: HealthCheck
    install:
      - docker run -v $(pwd)/demos/projects:/io/data -v $(pwd)/plugins:/io/plugins -d -p 8015:80 openquake/qgis-server:stable
    script:
      - sleep 10 && curl http://localhost:8015/ogc/nepal_hazard?service=HC
