services: docker
language: python

jobs:
  include:
  - stage: build
    env: CustomProperties
    install:
      - docker run -v $(pwd)/demos/projects:/io/data -v $(pwd)/plugins:/io/plugins -d -p 8015:80 openquake/qgis-server:stable
    script:
      - curl http://localhost:8015/ogc/nepal_hazard?SERVICE=WMS&REQUEST=GetCapabilities
      - curl http://localhost:8015/ogc/nepal_hazard?SERVICE=EWMS&REQUEST=GetCustomPropertiesByLayerName
      - curl http://localhost:8015/ogc/nepal_hazard?SERVICE=EWMS&REQUEST=GetCustomPropertiesByLayerId

